// Alphabetize and lint the medication list
export const DEFAULT_MEDICATIONS = [
  {
    genericName: 'Acetaminophen',
    brandName: 'Tylenol',
    dosageForm: 'tablet',
    strength: '500',
    unit: 'mg',
    rxcui: '161',
    ndc: '0046-1941-81',
    category: 'analgesic',
    description: 'Pain reliever and fever reducer',
  },
  {
    genericName: 'Albuterol',
    brandName: 'Ventolin',
    dosageForm: 'inhaler',
    strength: '90',
    unit: 'mcg/actuation',
    rxcui: '197798',
    ndc: '0173-0682-20',
    category: 'bronchodilator',
    description: 'Relieves bronchospasm in asthma and COPD',
  },
  {
    genericName: 'Amoxicillin',
    brandName: 'Amoxil',
    dosageForm: 'capsule',
    strength: '500',
    unit: 'mg',
    rxcui: '723',
    ndc: '43598-0343-01',
    category: 'antibiotic',
    description: 'Penicillin antibiotic',
  },
  {
    genericName: 'Atorvastatin',
    brandName: 'Lipitor',
    dosageForm: 'tablet',
    strength: '20',
    unit: 'mg',
    rxcui: '83367',
    ndc: '0006-0575-68',
    category: 'antihyperlipidemic',
    description: 'Statin for cholesterol management',
  },
  {
    genericName: 'Ceftriaxone',
    brandName: 'Rocephin',
    dosageForm: 'injection',
    strength: '1',
    unit: 'g',
    rxcui: '617314',
    ndc: '0409-7331-01',
    category: 'antibiotic',
    description: 'Cephalosporin antibiotic',
  },
  {
    genericName: 'Dexamethasone',
    brandName: 'Decadron',
    dosageForm: 'tablet',
    strength: '4',
    unit: 'mg',
    rxcui: '315002',
    ndc: '0003-0293-50',
    category: 'corticosteroid',
    description: 'Anti-inflammatory steroid',
  },
  {
    genericName: 'Diphenhydramine',
    brandName: 'Benadryl',
    dosageForm: 'tablet',
    strength: '25',
    unit: 'mg',
    rxcui: '197798',
    ndc: '50580-506-20',
    category: 'antihistamine',
    description: 'Allergy relief',
  },
  {
    genericName: 'Enoxaparin',
    brandName: 'Lovenox',
    dosageForm: 'injection',
    strength: '40',
    unit: 'mg/0.4mL',
    rxcui: '617314',
    ndc: '0002-4187-01',
    category: 'anticoagulant',
    description: 'Low molecular weight heparin',
  },
  {
    genericName: 'Furosemide',
    brandName: 'Lasix',
    dosageForm: 'injection',
    strength: '10',
    unit: 'mg/mL',
    rxcui: '202991',
    ndc: '0013-1024-01',
    category: 'diuretic',
    description: 'Loop diuretic for edema and hypertension',
  },
  {
    genericName: 'Heparin',
    brandName: 'Heparin Sodium',
    dosageForm: 'injection',
    strength: '1000',
    unit: 'units/mL',
    rxcui: '197361',
    ndc: '25021-020-10',
    category: 'anticoagulant',
    description: 'Anticoagulant for prevention of blood clots',
  },
  {
    genericName: 'Hydromorphone',
    brandName: 'Dilaudid',
    dosageForm: 'injection',
    strength: '2',
    unit: 'mg/mL',
    rxcui: '197798',
    ndc: '0409-1775-01',
    category: 'analgesic',
    description: 'Opioid pain medication',
  },
  {
    genericName: 'Insulin Regular',
    brandName: 'Humulin R',
    dosageForm: 'injection',
    strength: '100',
    unit: 'units/mL',
    rxcui: '705129',
    ndc: '0002-8215-01',
    category: 'antidiabetic',
    description: 'Short-acting insulin',
  },
  {
    genericName: 'Ibuprofen',
    brandName: 'Advil',
    dosageForm: 'tablet',
    strength: '200',
    unit: 'mg',
    rxcui: '5640',
    ndc: '0573-0169-28',
    category: 'analgesic',
    description: 'Nonsteroidal anti-inflammatory drug (NSAID)',
  },
  {
    genericName: 'Lisinopril',
    brandName: 'Prinivil',
    dosageForm: 'tablet',
    strength: '10',
    unit: 'mg',
    rxcui: '29046',
    ndc: '0006-0995-68',
    category: 'antihypertensive',
    description: 'ACE inhibitor for high blood pressure',
  },
  {
    genericName: 'Metformin',
    brandName: 'Glucophage',
    dosageForm: 'tablet',
    strength: '500',
    unit: 'mg',
    rxcui: '860975',
    ndc: '66993-0017-02',
    category: 'antidiabetic',
    description: 'Oral diabetes medicine',
  },
  {
    genericName: 'Metoprolol',
    brandName: 'Lopressor',
    dosageForm: 'tablet',
    strength: '50',
    unit: 'mg',
    rxcui: '197361',
    ndc: '0007-4201-68',
    category: 'antihypertensive',
    description: 'Beta blocker for blood pressure and heart rate',
  },
  {
    genericName: 'Morphine',
    brandName: 'Morphine Sulfate',
    dosageForm: 'injection',
    strength: '10',
    unit: 'mg/mL',
    rxcui: '315002',
    ndc: '0409-2310-01',
    category: 'analgesic',
    description: 'Opioid pain medication',
  },
  {
    genericName: 'Ondansetron',
    brandName: 'Zofran',
    dosageForm: 'tablet',
    strength: '4',
    unit: 'mg',
    rxcui: '315002',
    ndc: '0004-1962-01',
    category: 'antiemetic',
    description: 'Prevents nausea and vomiting',
  },
  {
    genericName: 'Pantoprazole',
    brandName: 'Protonix',
    dosageForm: 'tablet',
    strength: '40',
    unit: 'mg',
    rxcui: '617314',
    ndc: '0008-0841-81',
    category: 'proton pump inhibitor',
    description: 'Reduces stomach acid',
  },
  {
    genericName: 'Vancomycin',
    brandName: 'Vancocin',
    dosageForm: 'injection',
    strength: '1',
    unit: 'g',
    rxcui: '617314',
    ndc: '0409-6531-01',
    category: 'antibiotic',
    description: 'Glycopeptide antibiotic',
  },
].sort((a, b) => a.genericName.localeCompare(b.genericName));
